language: java
jdk:
- openjdk8
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: Pao4y1cV5CODZTO7vg9AbDS9G+uiUbGnr4zyRqaAu4EIbW79f33dzn0bMgc0TwUlf0AuOC1E4ywLK9ao7NMuspU6zrIBCHjo5Nmgn4Rms4CHObkeRUzo32yHanz2rby3S8esXMDYqxF7WgsBCfsqYt3Cn3auysf5BDDKo5lPrLR5ZS7mzaJDjO7S2Aw1Qlk14dYjFeKgIMGmlBX7JCDivj5ElLxoZO+7l6vb05K8KPDgRGoPr1JWLhJ43S1GzqwSjnI2L67fh/TSCBOXgHTtlX36dzmeIF+rGPjo0Kiyk9k8WVfsZfh/JUYfkfbeKMP6jCvBszm0xFXEFSG3KX3XnoMzGHvaEFcN98Fer1Z67fXgEblZO0r5kvSXq23BBY687RrsoEsYOPx4mp+yR/X7vbXAIw9qsxemx3t4qPNWmaCmLpJ2UMbXNeOEvLsjyNrRDvY5IC8x/Uqu/PdgAIcUwU22MQMWq1PQ/inFgg3K3tXmFWwue7OVnxkoWuXdgp1aEF0rL6f+l89+BqZftRzNgrlQN4sSyWUBpPpUk2jsxCiGIUVK5QXYmybXbY7ZDTeBqxJAzTjA/RLSJpOuRRAbaZriP+SkfvnCdKWXeftlkr9W5sTk7vJUone8Hu2rR5ukxbeXiAFcWULhsc+deqroGS3219OWw4ZfDEEy4jLD4T0=
  - secure: wRbCrDZCg7OywhToKwG6eTMvT65bCtRwSs3XefyfGiUoTokyCgnRC/wHzF+YOhHuo1HYX7rm5YOZ03jQfD0l6bsyTRJytbEESw1P8Chv4eCdji3/qrNt9j9bzjEOJG0YwU6E0DzBEffxX8l+fhKDiFN9IY/PS8LW3WZ5Eywn4Sk6dYDRuejyVHMBCrzSY9LcPUrODmm93zscVqExP04K8LAJJ/glFEHIoSyHp0BOS7m961IByNUsycTL9nYTOWd6QoWcLizRqHdcyzV8p1nEuItX5WQKHLomA5zEKjSOwfBdwGAFThHSroWHo/uLQWmjPNRs7yoW0vSJWGkkOKe0TrbJ3u4d1QJ0gD5LXe33YYV9NIZ26T1aOLVUqrmcRNS5C+A1HJF0GZq/X14vBuZDprjudOWfP7iIqu4Qtr5cti+tVlcRjRf0CHsz6pcEG97My+ToiEsiVU/BLhMqyjvC7VN5WEUgZdpUDeVmaMLYWedsNWBDrNdbOAHy5P96Dj9I4v4H/cyu8FJ3FqbRsOKuFmyXkZhXwHHVmOcdszJj5THQQt2WR3h6wbNXhbBf0N8IQGE8uGOhEN4h1tz0+Y3ttDUKfOCxx9hkr/fvcKTEF6Ynrlm/15LZoqCSkFBOBbwI2LJtc/SAsmZBKm566+l3gesGzcjWoxtmdMJ3/JGaQXM=
  - secure: AfRrffJI3oOXNOyrwqi5VOQDrpWgG4O0EoYDg2bnYkI8+CcqhnnFu+3exDBl1fzlNGx2HVPmkraRw3Vl203y/vNyRrxkNQMAlyBGH35zh2O4Va1DoRl7Iv3fdzWA2vmDEvHrZ/huUsYKeKTSZUyP4UeDpE2KyIgQI9ox1hpzPqL186gzu6VZp3KlkWiOoMaKPiN1T+zAlsdGEHqwMtpm3IWVs/WU711kgKOp95U0evqEoVy3OEkrU7DxPHgxyOepMComOs2xHQ4Ts8xdFl2jZVB4kvT+Y5WK2Chzf4YXQet+Wi95lt3y3PiAksykYOzqZz/wALiuO7W9MsY0B9Ar+xneyRDwe6dYmf8nHxZEoDuqYhdr18yrfpEOimwnlXySoWY9Nf61HQNajXJSNaoBxnVBR25oAa7yPLVTp/0+7oH+J+ZxOkQa38+F8DvsN5DjutD1GzxXBvVZvkeqfHJgMF8mKbc3TuIgqoJy12Gc0l8XoCyC6eC6VQVswPVrDHupQ+WUMKG8RmRmlkBKJQLE8aONExD1yUP12bGHlENJP8TjO1tkdnOe2AMl+D3UtIMc35qcQdw4j998ekyuu1thtPhu4BNxmQ3Fsm3iAmvWVO26nBUB44pQLN75IU3EXmyat2xzfktR2o7LtDcJeW+uzZyHwpx/MQgDyO5R3/nOvBQ=
before_install:
- docker pull bitnami/tomcat:8.0
script:
- mvn clean install -B
after_success:
- export COMMIT=${TRAVIS_COMMIT::7}
- export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH-$COMMIT";
  fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker build . -t $IMAGE_NAME:latest
- docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:latest
- docker push $IMAGE_NAME:$TAG
- export TITLE="$IMAGE_NAME:$TAG is built properly and pushed to Dockerhub"
- export TIMESTAMP=`date`
- export GIT_LOG=`git log -1 --pretty=%B $COMMIT`
- export TEXT="[build version] $TAG<br />[datetime] $TIMESTAMP<br />[changelog] $GIT_LOG<br
  />"
cache:
  directories:
  - "$HOME/.m2/repository"
